# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'PhotoViewer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'KFSwiftImageLoader', '~> 3.0'
  pod 'IGListKit', '~> 3.0'
  pod 'Hero'
  pod 'Reusable'
  
end
